server:
  port: 8081

spring:
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html
    encoding: UTF-8
  resources:
    static-locations: ["classpath: /META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/"]

